import type { Pair, Job, JobHousePair } from './types'
import { unsplashFixed } from './photos'

export const fixedPairs: Pair[] = [
  {
    id: "pair-1",
    job: {
      id: "job-1",
      title: "製造スタッフ",
      employer: "株式会社東京精密",
      wage: "¥1,250/hour",
      location: "東京都・足立区",
      type: "Full-time",
    },
    house: {
      id: "house-1",
      name: "北千住アパートメント",
      rent: "¥65,000",
      station: "徒歩5分",
      photo: unsplashFixed('house-1'),
      tags: ["家具付き", "駅近"],
    },
  },
  {
    id: "pair-2",
    job: {
      id: "job-2",
      title: "飲食スタッフ",
      employer: "イタリアンレストラン・ローマ",
      wage: "¥1,150/hour",
      location: "神奈川県・横浜市",
      type: "Part-time",
    },
    house: {
      id: "house-2",
      name: "横浜駅前マンション",
      rent: "¥78,000",
      station: "徒歩8分",
      photo: unsplashFixed('house-2'),
      tags: ["静かな住宅街", "シェアハウス"],
    },
  },
  {
    id: "pair-3",
    job: {
      id: "job-3",
      title: "介護スタッフ",
      employer: "介護福祉センター",
      wage: "¥1,350/hour",
      location: "愛知県・名古屋市",
      type: "Full-time",
    },
    house: {
      id: "house-3",
      name: "名古屋緑区アパート",
      rent: "¥55,000",
      station: "徒歩12分",
      photo: unsplashFixed('house-3'),
      tags: ["家具付き", "静かな住宅街"],
    },
  },
  {
    id: "pair-4",
    job: {
      id: "job-4",
      title: "倉庫スタッフ",
      employer: "物流株式会社",
      wage: "¥1,180/hour",
      location: "大阪府・大阪市",
      type: "Full-time",
    },
    house: {
      id: "house-4",
      name: "大阪北区マンション",
      rent: "¥68,000",
      station: "徒歩7分",
      photo: unsplashFixed('house-4'),
      tags: ["駅近", "シェアハウス"],
    },
  },
  {
    id: "pair-5",
    job: {
      id: "job-5",
      title: "清掃スタッフ",
      employer: "ビルメンテナンス株式会社",
      wage: "¥1,200/hour",
      location: "福岡県・福岡市",
      type: "Part-time",
    },
    house: {
      id: "house-5",
      name: "福岡中央アパート",
      rent: "¥62,000",
      station: "徒歩6分",
      photo: unsplashFixed('house-5'),
      tags: ["家具付き", "駅近"],
    },
  },
  {
    id: "pair-6",
    job: {
      id: "job-6",
      title: "製造スタッフ",
      employer: "電子機器株式会社",
      wage: "¥1,300/hour",
      location: "東京都・品川区",
      type: "Full-time",
    },
    house: {
      id: "house-6",
      name: "品川区高輪アパート",
      rent: "¥85,000",
      station: "徒歩3分",
      photo: unsplashFixed('house-6'),
      tags: ["駅近", "静かな住宅街"],
    },
  },
  {
    id: "pair-7",
    job: {
      id: "job-7",
      title: "介護スタッフ",
      employer: "高齢者福祉施設",
      wage: "¥1,320/hour",
      location: "神奈川県・川崎市",
      type: "Full-time",
    },
    house: {
      id: "house-7",
      name: "川崎区マンション",
      rent: "¥72,000",
      station: "徒歩9分",
      photo: unsplashFixed('house-7'),
      tags: ["家具付き", "シェアハウス"],
    },
  },
  {
    id: "pair-8",
    job: {
      id: "job-8",
      title: "飲食スタッフ",
      employer: "和食レストラン・花",
      wage: "¥1,280/hour",
      location: "愛知県・豊田市",
      type: "Part-time",
    },
    house: {
      id: "house-8",
      name: "豊田市住宅",
      rent: "¥58,000",
      station: "徒歩11分",
      photo: unsplashFixed('house-8'),
      tags: ["静かな住宅街", "家具付き"],
    },
  },
  {
    id: "pair-9",
    job: {
      id: "job-9",
      title: "倉庫スタッフ",
      employer: "流通センター",
      wage: "¥1,220/hour",
      location: "大阪府・堺市",
      type: "Full-time",
    },
    house: {
      id: "house-9",
      name: "堺市アパート",
      rent: "¥61,000",
      station: "徒歩8分",
      photo: unsplashFixed('house-9'),
      tags: ["駅近", "家具付き"],
    },
  },
  {
    id: "pair-10",
    job: {
      id: "job-10",
      title: "清掃スタッフ",
      employer: "オフィス清掃サービス",
      wage: "¥1,160/hour",
      location: "福岡県・北九州市",
      type: "Part-time",
    },
    house: {
      id: "house-10",
      name: "北九州住宅",
      rent: "¥55,000",
      station: "徒歩10分",
      photo: unsplashFixed('house-10'),
      tags: ["シェアハウス", "静かな住宅街"],
    },
  },
  {
    id: "pair-11",
    job: {
      id: "job-11",
      title: "製造スタッフ",
      employer: "自動車部品メーカー",
      wage: "¥1,400/hour",
      location: "北海道・札幌市",
      type: "Full-time",
    },
    house: {
      id: "house-11",
      name: "札幌北区アパート",
      rent: "¥52,000",
      station: "徒歩7分",
      photo: unsplashFixed('house-11'),
      tags: ["家具付き", "駅近"],
    },
  },
  {
    id: "pair-12",
    job: {
      id: "job-12",
      title: "介護スタッフ",
      employer: "老人ホーム",
      wage: "¥1,380/hour",
      location: "宮城県・仙台市",
      type: "Full-time",
    },
    house: {
      id: "house-12",
      name: "仙台青葉区マンション",
      rent: "¥68,000",
      station: "徒歩5分",
      photo: unsplashFixed('house-12'),
      tags: ["駅近", "静かな住宅街"],
    },
  },
  {
    id: "pair-13",
    job: {
      id: "job-13",
      title: "飲食スタッフ",
      employer: "ファストフードチェーン",
      wage: "¥1,100/hour",
      location: "広島県・広島市",
      type: "Part-time",
    },
    house: {
      id: "house-13",
      name: "広島中区アパート",
      rent: "¥59,000",
      station: "徒歩6分",
      photo: unsplashFixed('house-13'),
      tags: ["家具付き", "シェアハウス"],
    },
  },
  {
    id: "pair-14",
    job: {
      id: "job-14",
      title: "倉庫スタッフ",
      employer: "物流倉庫",
      wage: "¥1,250/hour",
      location: "京都府・京都市",
      type: "Full-time",
    },
    house: {
      id: "house-14",
      name: "京都左京区住宅",
      rent: "¥75,000",
      station: "徒歩8分",
      photo: unsplashFixed('house-14'),
      tags: ["静かな住宅街", "駅近"],
    },
  },
  {
    id: "pair-15",
    job: {
      id: "job-15",
      title: "清掃スタッフ",
      employer: "商業施設清掃",
      wage: "¥1,190/hour",
      location: "兵庫県・神戸市",
      type: "Part-time",
    },
    house: {
      id: "house-15",
      name: "神戸中央アパート",
      rent: "¥66,000",
      station: "徒歩4分",
      photo: unsplashFixed('house-15'),
      tags: ["家具付き", "駅近"],
    },
  },
  {
    id: "pair-16",
    job: {
      id: "job-16",
      title: "製造スタッフ",
      employer: "精密機器メーカー",
      wage: "¥1,450/hour",
      location: "静岡県・静岡市",
      type: "Full-time",
    },
    house: {
      id: "house-16",
      name: "静岡葵区マンション",
      rent: "¥63,000",
      station: "徒歩9分",
      photo: unsplashFixed('house-16'),
      tags: ["シェアハウス", "家具付き"],
    },
  },
  {
    id: "pair-17",
    job: {
      id: "job-17",
      title: "介護スタッフ",
      employer: "訪問介護サービス",
      wage: "¥1,360/hour",
      location: "新潟県・新潟市",
      type: "Full-time",
    },
    house: {
      id: "house-17",
      name: "新潟中央区アパート",
      rent: "¥54,000",
      station: "徒歩11分",
      photo: unsplashFixed('house-17'),
      tags: ["静かな住宅街", "駅近"],
    },
  },
  {
    id: "pair-18",
    job: {
      id: "job-18",
      title: "飲食スタッフ",
      employer: "カフェチェーン",
      wage: "¥1,140/hour",
      location: "熊本県・熊本市",
      type: "Part-time",
    },
    house: {
      id: "house-18",
      name: "熊本中央住宅",
      rent: "¥57,000",
      station: "徒歩7分",
      photo: unsplashFixed('house-18'),
      tags: ["家具付き", "シェアハウス"],
    },
  },
  {
    id: "pair-19",
    job: {
      id: "job-19",
      title: "倉庫スタッフ",
      employer: "配送センター",
      wage: "¥1,210/hour",
      location: "沖縄県・那覇市",
      type: "Full-time",
    },
    house: {
      id: "house-19",
      name: "那覇市アパート",
      rent: "¥70,000",
      station: "徒歩6分",
      photo: unsplashFixed('house-19'),
      tags: ["駅近", "家具付き"],
    },
  },
  {
    id: "pair-20",
    job: {
      id: "job-20",
      title: "清掃スタッフ",
      employer: "ホテル清掃サービス",
      wage: "¥1,170/hour",
      location: "鹿児島県・鹿児島市",
      type: "Part-time",
    },
    house: {
      id: "house-20",
      name: "鹿児島中央マンション",
      rent: "¥56,000",
      station: "徒歩8分",
      photo: unsplashFixed('house-20'),
      tags: ["静かな住宅街", "シェアハウス"],
    },
  },
  {
    id: "pair-21",
    job: {
      id: "job-21",
      title: "製造スタッフ",
      employer: "食品加工会社",
      wage: "¥1,290/hour",
      location: "千葉県・千葉市",
      type: "Full-time",
    },
    house: {
      id: "house-21",
      name: "千葉中央区アパート",
      rent: "¥64,000",
      station: "徒歩10分",
      photo: unsplashFixed('house-21'),
      tags: ["家具付き", "駅近"],
    },
  },
  {
    id: "pair-22",
    job: {
      id: "job-22",
      title: "介護スタッフ",
      employer: "デイサービスセンター",
      wage: "¥1,340/hour",
      location: "埼玉県・さいたま市",
      type: "Full-time",
    },
    house: {
      id: "house-22",
      name: "さいたま大宮住宅",
      rent: "¥69,000",
      station: "徒歩5分",
      photo: unsplashFixed('house-22'),
      tags: ["駅近", "静かな住宅街"],
    },
  },
  {
    id: "pair-23",
    job: {
      id: "job-23",
      title: "飲食スタッフ",
      employer: "寿司レストラン",
      wage: "¥1,320/hour",
      location: "群馬県・前橋市",
      type: "Part-time",
    },
    house: {
      id: "house-23",
      name: "前橋市アパート",
      rent: "¥53,000",
      station: "徒歩12分",
      photo: unsplashFixed('house-23'),
      tags: ["家具付き", "シェアハウス"],
    },
  },
  {
    id: "pair-24",
    job: {
      id: "job-24",
      title: "倉庫スタッフ",
      employer: "小売倉庫",
      wage: "¥1,230/hour",
      location: "栃木県・宇都宮市",
      type: "Full-time",
    },
    house: {
      id: "house-24",
      name: "宇都宮中央マンション",
      rent: "¥60,000",
      station: "徒歩9分",
      photo: unsplashFixed('house-24'),
      tags: ["駅近", "家具付き"],
    },
  },
]

const houses = fixedPairs.map(p => p.house)

export const jobs: Job[] = [
  {
    id: 'job-1',
    employer: '高齢者福祉施設',
    position: '介護スタッフ',
    wage: '¥1,250/hour',
    location: '愛知県・名古屋市',
    type: 'Full-time',
    description: '高齢者の日常生活支援と身体介護を行います。',
    requirements: ['介護初任者研修修了', '日本語N3以上', 'やる気のある方'],
    benefits: ['社会保険完備', '昇給あり', '研修制度充実'],
  },
  {
    id: 'job-2', 
    employer: '介護福祉センター',
    position: '介護スタッフ',
    wage: '¥1,320/hour',
    location: '神奈川県・川崎市',
    type: 'Full-time',
    description: '利用者様の生活支援と介護業務全般を担当していただきます。',
    requirements: ['介護経験者優遇', '日本語N2以上', 'チームワークを大切にできる方'],
    benefits: ['交通費支給', '資格取得支援', '正社員登用あり'],
  },
]

export const jobHousePairs: JobHousePair[] = [
  {
    id: 'pair-25',
    job: jobs[0],
    house: houses[0], // 名古屋近郊用
  },
  {
    id: 'pair-26', 
    job: jobs[1],
    house: houses[1], // 神奈川近郊用
  },
]
